apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bases/inference.networking.k8s.io_inferencepools.yaml
- bases/inference.networking.x-k8s.io_inferenceobjectives.yaml
- bases/inference.networking.x-k8s.io_inferencemodelrewrites.yaml
- bases/inference.networking.x-k8s.io_inferencepoolimports.yaml
- bases/llm-d.ai_inferenceobjectives.yaml
- bases/llm-d.ai_inferencemodelrewrites.yaml
