{{ include "llm-d-router.validations.epp.resources" $ }}
{{ include "llm-d-router.validations.standalone" . }}
{{ include "inference-extension.config" . }}
{{ include "inference-extension.deployment" . }}
{{ include "inference-extension.gke" . }}
{{ include "inference-extension.lead-election-rbac" . }}
{{ include "inference-extension.sa-token-secret" . }}
{{ include "inference-extension.service" . }}
{{ include "inference-extension.service-monitor" . }}
{{ include "inference-extension.rbac" . }}
